### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Elmago27310** [joco73/se.cohen.renaultze#3]
Hello, would you like me to do the translation in French?

**Comment by joco73** [comment]
@Elmago27310 - yes that would be very nice 👍 
(and if you know NodeJS/JavaScript, any improvements and suggestions are welcome, i am not a super JavaScript programmer...)

**Comment by Elmago27310** [comment]
No, unfortunately I’m not an expert in it. What file should I translate?

**Comment by Elmago27310** [comment]
Hello @joco73 ,

I think I have translated everything, it's up to you

**Comment by joco73** [comment]
Great, thanks!
I will merge and add to a test version during the weekend

**Comment by joco73** [comment]
It is now merged and published to Homey as a test app -  I will let it be in test a couple of days and then publish live.
You can install it on: https://homey.app/sv-se/app/se.cohen.renaultze/Renault-Z.E./test/
