### ISSUE TITLE
Homey Pro 2023 Compatibility

### ISSUE THREAD

**Issue by CyB0rgg** [joco73/se.cohen.renaultze#36]
Just unwrapped my homey pro 2023 and sadly the Zoe device had red exclamation mark on it. Tried to reinstall the app - same issue. When adding the device it shows Renault Zoe with red triangle on it  - can't click on it to add it.

Did you have a chance to test it with the new Homey Pro 2023 or am I the 1st victim ?

Thanks !

**Comment by joco73** [comment]
Hi, I check the dev. tools log, not sure what error is from you - but latest error indicate som connections problem "EHOSTUNREACH". I have not tested with new Pro (have not one myself).

Could you go to app. setting and send a diagnostic report to me and I can check if I can figure something out?

**Comment by CyB0rgg** [comment]
Hi.

Report 12963bdb-9e90-4146-8b14-ea72753840da

Thanks

**Comment by joco73** [comment]
Hi @CyB0rgg 

Pease try test version, if it works come back to me and I will publish to production.
If still a problem, please send a new diagnostic report

https://homey.app/sv-se/app/se.cohen.renaultze/Renault-Z.E./test/

**Comment by CyB0rgg** [comment]
Seems to be working. I have managed to log in and add the car. The only difference I see is that when selecting the status indicator in the advanced settings choosing battery it does not display the battery symbol with green filling showing the battery left but it shows remaining range in km.
